# Generated by Django 4.2.19 on 2025-03-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('date_YYYYMMDD', models.DateField()),
                ('latitude_n', models.IntegerField()),
                ('longitude_w', models.IntegerField()),
                ('maxwind_knots', models.IntegerField()),
                ('minimum_pressure_mb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wiki_Storms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('date_YYYYMMDD', models.DateField()),
                ('latitude_n', models.IntegerField()),
                ('longitude_w', models.IntegerField()),
                ('maxwind_knots', models.IntegerField()),
                ('minimum_pressure_mb', models.IntegerField()),
                ('NE_34kt', models.IntegerField()),
                ('SE_34kt', models.IntegerField()),
                ('SW_34kt', models.IntegerField()),
                ('NW_34kt', models.IntegerField()),
                ('NE_50kt', models.IntegerField()),
                ('SE_50kt', models.IntegerField()),
                ('SW_50kt', models.IntegerField()),
                ('NW_50kt', models.IntegerField()),
                ('NE_64kt', models.IntegerField()),
                ('SE_64kt', models.IntegerField()),
                ('SW_64kt', models.IntegerField()),
                ('NW_64kt', models.IntegerField()),
                ('radius_max_wind', models.IntegerField()),
                ('radius_34', models.IntegerField()),
                ('radius_50', models.IntegerField()),
                ('radius_64', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Storm_Wiki_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formed_date', models.CharField(max_length=50)),
                ('dissipated_date', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('fatalities', models.CharField(max_length=50)),
                ('damage', models.CharField(max_length=100)),
                ('affected_areas', models.TextField()),
                ('storm', models.ForeignKey(db_column='codename', on_delete=django.db.models.deletion.CASCADE, related_name='wiki_data_entries', to='app.wiki_storms', to_field='codename')),
            ],
        ),
    ]
