# Generated by Django 4.2.19 on 2025-03-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storm_wiki_data',
            name='storm',
        ),
        migrations.AddField(
            model_name='wiki_storms',
            name='storm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storm_lines', to='app.storm_wiki_data'),
        ),
        migrations.AlterField(
            model_name='wiki_storms',
            name='latitude_n',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wiki_storms',
            name='longitude_w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wiki_storms',
            name='radius_34',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wiki_storms',
            name='radius_50',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wiki_storms',
            name='radius_64',
            field=models.FloatField(),
        ),
    ]
