# Generated by Django 4.2.19 on 2025-03-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_storm_wiki_data_storm_wiki_storms_storm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storm_wiki_data',
            name='affected_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storm_wiki_data',
            name='damage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storm_wiki_data',
            name='dissipated_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storm_wiki_data',
            name='fatalities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storm_wiki_data',
            name='formed_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
