# Generated by Django 4.2.19 on 2025-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_storm_wiki_data_affected_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstorms',
            name='codename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wiki_storms',
            name='codename',
            field=models.CharField(max_length=100),
        ),
    ]
