# Generated by Django 4.2.19 on 2025-03-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_allstorms_codename_alter_wiki_storms_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storm_wiki_data',
            name='damage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
