# Generated by Django 4.2.19 on 2025-03-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_storm_wiki_data_damage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstorms',
            old_name='date_YYYYMMDD',
            new_name='date_end_YYYYMMDD',
        ),
        migrations.AddField(
            model_name='allstorms',
            name='date_start_YYYYMMDD',
            field=models.DateField(default='1851-01-01'),
        ),
    ]
