# Generated by Django 4.2.19 on 2025-03-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_allstorms_current_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki_storms',
            name='minimum_pressure_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
