# Generated by Django 4.2.19 on 2025-03-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_wiki_storms_minimum_pressure_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstorms',
            name='minimum_pressure_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
