# Generated by Django 4.2.19 on 2025-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_allstorms_minimum_pressure_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstorms',
            name='time_24hr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
