# Generated by Django 4.2.19 on 2025-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_allstorms_time_24hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StormOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('centre_latitude_n', models.FloatField()),
                ('centre_longitude_w', models.FloatField()),
                ('radius_from_centre', models.FloatField()),
                ('highest_classification', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
