# Generated by Django 4.2 on 2025-05-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_stormoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaSurfaceTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('annual_anomaly', models.FloatField()),
            ],
        ),
    ]
