# Generated by Django 4.2 on 2025-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_seasurfacetemperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('m1', models.FloatField(blank=True, null=True)),
                ('m2', models.FloatField(blank=True, null=True)),
                ('m3', models.FloatField(blank=True, null=True)),
                ('m4', models.FloatField(blank=True, null=True)),
                ('m5', models.FloatField(blank=True, null=True)),
                ('m6', models.FloatField(blank=True, null=True)),
                ('m7', models.FloatField(blank=True, null=True)),
                ('m8', models.FloatField(blank=True, null=True)),
                ('m9', models.FloatField(blank=True, null=True)),
                ('m10', models.FloatField(blank=True, null=True)),
                ('m11', models.FloatField(blank=True, null=True)),
                ('m12', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_mei',
            },
        ),
    ]
