# Generated by Django 4.2 on 2025-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_monthlymei'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedTimeseriesWithMei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('centre_latitude_n', models.FloatField()),
                ('centre_longitude_w', models.FloatField()),
                ('radius_from_centre', models.FloatField()),
                ('highest_classification', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('annual_anomaly', models.FloatField()),
                ('max_wind', models.IntegerField()),
                ('start_month', models.IntegerField()),
                ('mei', models.FloatField()),
            ],
            options={
                'db_table': 'enriched_timeseries_with_mei',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StormCountsWithPredictors',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('start_month', models.IntegerField()),
                ('storm_count', models.IntegerField()),
                ('avg_mei', models.FloatField()),
                ('annual_anomaly', models.FloatField()),
            ],
            options={
                'db_table': 'storm_counts_with_predictors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictedStorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('mei', models.FloatField()),
                ('predicted_storm_wind', models.CharField(max_length=20)),
                ('predicted_storm_radius_km', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Predicted Storm',
                'verbose_name_plural': 'Predicted Storms',
                'db_table': 'predicted_storms',
            },
        ),
    ]
